### ISSUE TITLE
Make dreamtools python 3 compatiable

### ISSUE THREAD

**Issue by cokelaer** [dreamtools/dreamtools#61]

**Comment by cokelaer** [comment]
This is now done. A new version has been added to Pypi and all tests seem to pass successfully

**Comment by khinsen** [comment]
Installation still fails under Python 3. The problematic dependency is `gevent`:
```
Downloading/unpacking gevent (from grequests->bioservices->biokit->dreamtools)
  Downloading gevent-1.0.2.tar.gz (1.7MB): 1.7MB downloaded
  Running setup.py (path:/Users/hinsen/Temp/dreamtools/build/gevent/setup.py) egg_info for package gevent
```

`gevent 1.0.2` does not claim to be compatible with Python 3, and indeed its installation fails because of a Python 2 `print` statement:
```
  Running setup.py install for gevent
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/hinsen/Temp/dreamtools/build/gevent/setup.py", line 317, in <module>
        run_setup(ext_modules)
      File "/Users/hinsen/Temp/dreamtools/build/gevent/setup.py", line 312, in run_setup
        "Development Status :: 4 - Beta"])
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/hinsen/Temp/dreamtools/lib/python3.4/site-packages/setuptools/command/install.py", line 59, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/Users/hinsen/Temp/dreamtools/build/gevent/setup.py", line 234, in build_extension
        self.gevent_prepare(ext)
      File "/Users/hinsen/Temp/dreamtools/build/gevent/setup.py", line 231, in gevent_prepare
        configure(self, ext)
      File "/Users/hinsen/Temp/dreamtools/build/gevent/setup.py", line 139, in configure_libev
        make_universal_header('config.h', 'SIZEOF_LONG', 'SIZEOF_SIZE_T', 'SIZEOF_TIME_T')
      File "/Users/hinsen/Temp/dreamtools/build/gevent/setup.py", line 111, in make_universal_header
        print >>f, line
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
```
